name: lyzor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0
  mime: ^2.0.0
  watcher: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  lizard: lyzor